### ISSUE TITLE
Update hard-switching routines from greenlet

### ISSUE THREAD

**Issue by ghost** [stackless-dev/stackless#10]
Originally reported by: **RMTEW FULL NAME (Bitbucket: [rmtew](https://bitbucket.org/rmtew), GitHub: [rmtew](https://github.com/rmtew))**

----------------------------------------

(originally reported in Trac by @rmtew on 2012-07-23 03:05:10)

Greenlet has updated versions of Stackless' hard switching routines.  It would be worthwhile to update these for Stackless where suitable.

One way in which it may not be suitable, is that Stackless is under the PSF license.  And greenlet is under some confused mix of the MIT and PSF license, due to the confused authorship of Stackless-sourced files within it.

Any that are obviously derived from Stackless versions, should be PSF licensed.

Kristjan, should we consider this for the 3.3 release?

----------------------------------------
- Bitbucket: https://bitbucket.org/stackless-dev/stackless/issue/10

**Comment by akruis** [comment]
@kristjanvalur To answer your comment in PR #163 

You wrote a good summary. For 2.7. it is probably not worth the effort. One more year and than 2.7 is history.

We suspended our discussion about this topic nearly 5 years ago, but issue #10 is still open. since the the  situation changed a bit: the test suite is better and more complete, memory leaks are gone, git simplifies the development workflow. Therefore I'm willing to review and approve pull requests. But don't expect me to do all the work myself. I maintain Stackless in my leisure time and the preparation of new minor versions (like 3.7) takes a lot of time.

**Comment by kristjanvalur** [comment]
In the years since I left CCP Games, I have had very little to do with core python development, including Stackless.  Pressures of work mean that I don't have much time to contribute.  Once in a while I do revisit some toy projects, including the tealet project.  But that hasn't been updated in a while.  Also, I don't know what is the current states of low level switching routines.  There is some mismatch between all three, stackless, greenlets, and tealets.  The latter (Anselm Kruis' latest foray into this) removes the needs for static variables.  
But there are other differences, for example the amount of state that is saved.  I wrote the original x64 switching code for stackless, and was careful to save _all_ processor state that the ABI didn't specify as volatile.  This included some FPU state and SSE2, if I remember correctly.  I think we should try to at least reconcile some of this code into some best of breed stuff.

**Comment by akruis** [comment]
Outdated by pull request #230 (stackman).
